inherit_from: .rubocop_todo.yml

plugins:
  - rubocop-internal_affairs
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec
  - rubocop-rspec-extra

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7
  SuggestExtensions: false

Layout/LineLength:
  Enabled: false

Metrics:
  Enabled: false

Naming/FileName:
  Exclude:
    - lib/rubocop-rspec-extra.rb

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

RSpec/ExampleLength:
  Enabled: false
