---
RSpec/Extra:
  Enabled: true

RSpec/Extra/BeEmpty:
  Description: Prefer using `be_empty` when checking for an empty array.
  Enabled: pending
  VersionAdded: '0.1'
  Reference: https://www.rubydoc.info/gems/rubocop-rspec-extra/RuboCop/Cop/RSpec/Extra/BeEmpty

RSpec/Extra/FlatExamples:
  Description: 'Restrict unnecessary nesting by example groups.'
  Enabled: false
  VersionAdded: '<<next>>'

RSpec/Extra/RestrictBlockTag:
  Description: 'Restrict to only allowed block tags.'
  Enabled: false
  VersionAdded: '0.1'
  AllowTags: []

RSpec/Extra/RestrictBlockTagValue:
  Description: 'Restrict to only allowed block tag value.'
  Enabled: pending
  VersionAdded: '0.1'
  AllowTagValues: {}
