---
RSpec/Extra:
  Enabled: true

RSpec/Extra/BeEmpty:
  Description: Prefer using `be_empty` when checking for an empty array.
  Enabled: pending
  VersionAdded: '<<next>>'
  Reference: https://www.rubydoc.info/gems/rubocop-rspec-extra/RuboCop/Cop/RSpec/Extra/BeEmpty

RSpec/Extra/RestrictBlockTag:
  Description: 'Restrict to only allowed block tags.'
  Enabled: false
  VersionAdded: '<<next>>'
  AllowTags: []
